### ISSUE TITLE
Wanted quality not working

### ISSUE THREAD

**Issue by Esriimm** [Alissonsleal/TwitchSubVod#102]
It seems like when you try to switch quality it's not responding anymore. Lets say i have low internet connection, so i want 720p but the videos always load with source quality no matter what quality you have chosen, and that makes buffer and lag a lot. 
Please fix that.

**Comment by Alissonsleal** [comment]
True, thank you for letting me know, I'll fix this later today

**Comment by Esriimm** [comment]
Thank you for your reactivity.Keep up the good work.Envoyé depuis mon appareil Galaxy
-------- Message d'origine --------De : Alisson Leal ***@***.***> Date : 12/08/2021  15:54  (GMT+01:00) À : Alissonsleal/TwitchSubVod ***@***.***> Cc : Esriimm ***@***.***>, Author ***@***.***> Objet : Re: [Alissonsleal/TwitchSubVod] Wanted quality not working (#102) 
True, thank you for letting me know, I'll fix this later today

**Comment by Alissonsleal** [comment]
Fixed, can you check? You can only change the quality when you see all the streamer videos now

**Comment by Esriimm** [comment]
Nice, it's working perfectly.Great job.Envoyé depuis mon appareil Galaxy
-------- Message d'origine --------De : Alisson Leal ***@***.***> Date : 13/08/2021  03:41  (GMT+01:00) À : Alissonsleal/TwitchSubVod ***@***.***> Cc : Esriimm ***@***.***>, Author ***@***.***> Objet : Re: [Alissonsleal/TwitchSubVod] Wanted quality not working (#102) 
Fixed, can you check? You can only change the quality when you see all the streamer videos now
