### ISSUE TITLE
iOS 15.1 video player is broken

### ISSUE THREAD

**Issue by valentinene** [Alissonsleal/TwitchSubVod#121]
On iOS 15.1 video player is broken on any browser. I tried on iPhone X with safari, chrome and brave and after the captcha clicking on the play button does nothing.

**Comment by Alissonsleal** [comment]
Does this still happen to you @valentinene ?
I asked other people and it seems to be working.

Closing this for now, let me know if it happens again so I can re-open it

**Comment by valentinene** [comment]
It’s working now, thanks!
