### ISSUE TITLE
« Support me » button

### ISSUE THREAD

**Issue by IlanZ93** [Alissonsleal/TwitchSubVod#125]
Hello Alisson,

As you can see, the "Support me" button in annoying when video is in full screen mode (well, fake full screen). The button hinders access to play/pause and sound buttons.

![image](https://user-images.githubusercontent.com/23208231/147007248-a5d835b1-827e-4989-a21f-c588d15aa68d.png)

![image](https://user-images.githubusercontent.com/23208231/147007375-873334d4-9a80-45e6-b94f-a034e8c2e4d8.png)

Also is it possible to add go forward/backward buttons ? Like native iOS player +15sec -15sec, or more like 30sec ?

Thank you

**Comment by Alissonsleal** [comment]
Good catch. We're developing a brand new website experience and I don't think we'll have this floating button, and we'll definitely add `-15s | +15s` buttons

For now I recommend just making it fullscreen to play/pause.
