### ISSUE TITLE
404 error on Deleted VOD

### ISSUE THREAD

**Issue by IlanZ93** [Alissonsleal/TwitchSubVod#143]
Hi,

I'm getting a 404 error while i try to look at Deleted VOD on the V2.

On the V1, im getting another error, "An unexpected error has occurred.". Yesterday was another message about the API.

![image](https://user-images.githubusercontent.com/23208231/157405483-99cceb60-0750-4e0d-ad54-006c89f02015.png)

**Comment by BlueTankEngine** [comment]
Recreated the same error on all update channels of Chrome & Firefox. Possibly another backend change like what happened in the fall?

**Comment by IlanZ93** [comment]
Here its on Chrome but i have the issue on Safari too. Havent tried on computer.
