### ISSUE TITLE
issue browser mobile - player don't work

### ISSUE THREAD

**Issue by TestCs50Test** [Alissonsleal/TwitchSubVod#65]
Hi, on the brower mobile - Safari or Brave - on Iphone or Ipad don't work well. Anyway i have no problem on web browser. You can see an example:

<img width="895" alt="Immagine PNG" src="https://user-images.githubusercontent.com/47751426/114266427-9ffb8e80-99f6-11eb-9a5a-8bb3dc2ee06f.png">

Any soluction? 
Thank you
Pablo

**Comment by Alissonsleal** [comment]
HLS is not supported on iOS, i don't really know how to resolve that yet 
[issue](https://github.com/cookpete/react-player/issues/1019#issuecomment-695357636)
