### ISSUE TITLE
Twitch uploaded videos don't work

### ISSUE THREAD

**Issue by Esriimm** [Alissonsleal/TwitchSubVod#70]
An issue that i encountered is when i want to watch an uploaded video by the streamer himself it says "We couldn't find this video" or sometimes "We couldn't find this video, try changing the quality to 'Source' " and this happens only on uploaded videos. I hope this will be fixed as soon as possible. 

Screenshots below of the issue:

![Screenshot_20210501-000756_Samsung Internet](https://user-images.githubusercontent.com/83479391/116762162-7c35d200-aa11-11eb-8a49-ff07bc989e54.jpg)

![Screenshot_20210501-000844_Samsung Internet](https://user-images.githubusercontent.com/83479391/116762224-a2f40880-aa11-11eb-97c9-64a22d15f587.jpg)

**Comment by Alissonsleal** [comment]
Can you tell me the streamer name so I can research further?

**Comment by Esriimm** [comment]
> Can you tell me the streamer name so I can research further?

It happens with all manually uploaded videos by any streamer, let me give you an example: i want to watch an uploaded video from a streamer called "Liberto", posted on 29 April it doesn't work, and i also tried with older videos it's the same problem, even with VPN on/off, or changing my browser, trying it on PC... Always the same issue.

Thank you for your quick response.

**Comment by Alissonsleal** [comment]
fixed, can you try it now? @Esriimm

**Comment by Esriimm** [comment]
> fixed, can you try it now? @Esriimm

Ohh nice it works properly very good job. Thank you for your great work and serious. :)
