### ISSUE TITLE
pogu.live won't show sub-only vods

### ISSUE THREAD

**Issue by makiele** [Alissonsleal/TwitchSubVod#74]
Hi

I tried to access a sub-only vod via `pogu.live`. when entering the vod-url and and clicking "Search" the spinning wheel will just go indefinitely without any error.

However, I was able to access the vod via other means despite not being subbed.

Any idea why it does not work on pogu.live? May it have something to do with twitchtracker blocking page source?

thank you

**Comment by Alissonsleal** [comment]
Can I get the streamer name so I can look further?

**Comment by makiele** [comment]
of course, here is an example
https://www.twitch.tv/videos/1020117693

**Comment by Alissonsleal** [comment]
It's working fine https://pogu.live/videos/jay_corner
