### ISSUE TITLE
Videos do not play on iPad

### ISSUE THREAD

**Issue by l0u1sg** [Alissonsleal/TwitchSubVod#83]
Hello,

I have a small problem, I can't play videos with my iPhone/iPad, I have no error and all content blockers are disabled.

Here is the screenshot:
![D8657B96-2C92-47B5-9DF4-03CA079572F8](https://user-images.githubusercontent.com/46707587/120905758-8ff9d700-c654-11eb-9ba3-628fdd121d0c.png)

**Comment by Alissonsleal** [comment]
Same as #65 

HLS is not supported on iOS, I don't really know how to resolve that yet 
[issue](https://github.com/cookpete/react-player/issues/1019#issuecomment-695357636)

**Comment by pmorgf** [comment]
> Same as #65
> 
> HLS is not supported on iOS, I don't really know how to resolve that yet
> [issue](https://github.com/cookpete/react-player/issues/1019#issuecomment-695357636)

Apple created the standard HLS and it is what is used for streaming regularly. Maybe could be something else?

**Comment by Alissonsleal** [comment]
I just merged a fix, can you let me know if it's working @l0u1sg @pmorgf ?

**Comment by l0u1sg** [comment]
Yeah, it’s working, thanks !

-- 


This message contains confidential information and is intended only for 
the 
individual named. If you are not the named addressee you should not 
disseminate, 
distribute or copy this e-mail. Please notify the sender 
immediately by e-mail 
if you have received this e-mail by mistake and 
delete this e-mail from your 
system. E-mail transmission cannot be 
guaranteed to be secure or error-free as 
information could be intercepted, 
corrupted, lost, destroyed, arrive late or 
incomplete, or contain viruses. 
The sender therefore does not accept liability 
for any errors or omissions 
in the contents of this message, which arise as a 
result of e-mail 
transmission. If verification is required please request a 
hard-copy 
version. Simonian Educational Foundation, Halabyan 16, Yerevan, Rep. of 
Armenia. www.tumo.org <http://www.tumo.org>

**Comment by pedramp20** [comment]
I am facing the same issue. What version has the changes? Does it support HLS with authorisation? @Alissonsleal @l0u1sg
