### ISSUE TITLE
is there a way to download the vods?

### ISSUE THREAD

**Issue by eisamstiel** [Alissonsleal/TwitchSubVod#88]
i cant find anything about this on the site

**Comment by Alissonsleal** [comment]
We haven't developed anything to download the vod.
You can try downloading with any m3u8 downloader, like this one: https://chrome.google.com/webstore/detail/m3u8-online-video-extract/fcpefnjbneopahdnhdhahbhoccipdmdm I haven't tested it, not sure if it works
