### ISSUE TITLE
subs vod not found video

### ISSUE THREAD

**Issue by 0xAkashsec** [Alissonsleal/TwitchSubVod#89]
![18558](https://user-images.githubusercontent.com/46501627/124365581-e6196480-dc6a-11eb-9e33-ce95410609d8.png)

**Comment by Alissonsleal** [comment]
Can you provide more information? Like streamer name and vod name/date?

**Comment by 0xAkashsec** [comment]
![image](https://user-images.githubusercontent.com/46501627/124366003-0f87bf80-dc6e-11eb-92fd-2084316ca4b5.png)

https://pogu.live/videos/teomewhy
[Data Science] GridSearch e RandomSearch e RandomizedSearch

**Comment by Alissonsleal** [comment]
Looks like it's a "highlight" vod instead of an "archive" vod, fixing it right now

**Comment by 0xAkashsec** [comment]
Superman. That is full video man. I don't know. But video length 2 hours 7 munites.

**Comment by Alissonsleal** [comment]
Fixed, can you check @0xAkashsec ?

**Comment by 0xAkashsec** [comment]
> Fixed, can you check @0xAkashsec ?

What a boss coder... OP boss🥰🥰
