### ISSUE TITLE
Player unable to play any video on iOS 13.5.1

### ISSUE THREAD

**Issue by Qu3nt174** [Alissonsleal/TwitchSubVod#91]
The website seems to not be able to launch vods.
It shows the player with the crossed play button.

**Comment by pmorgf** [comment]
Currently on iOS 14 and no vods will play. It just has a slash through the video player icon

**Comment by EvPatko** [comment]
Yea that happens to me too. Is there a way to fix it?

**Comment by Alissonsleal** [comment]
I just merged a fix, can you check @Qu3nt174 @EvPatko ?

**Comment by Qu3nt174** [comment]
Working like a charm !!!
